export const ROUTES = {
  SIGN_UP: '/signup',
  SIGN_IN: '/signin',
  USER_CARDS: '/',
  USER_CARDS_DETAILS: '/:cardId',
  PROFILE: '/profile',
  AUCTIONS: '/auctions',
  CHATS: '/chats',
  CARDS: '/cards',
  CREATE_CARD: '/create-card',
  SETS: '/sets',
  CREATE_SET: '/sets-create',
  STATISTICS: '/statistics',
  USERS: '/users',
  TRANSACTIONS: '/transactions',
  LOCATIONS: '/locations',
  CREATE_LOCATION: '/locations/create',
  EDIT_LOCATION: '/locations/edit/:locationId',
  EPISODES: '/episodes',
  CREATE_EPISODE: '/episodes/create',
  EDIT_EPISODE: '/episodes/edit/:episodeId',
};
