export const ROUTES = {
  SIGN_UP: '/signup',
  SIGN_IN: '/signin',
  USER_CARDS: '/',
  PROFILE: '/profile',
  AUCTIONS: '/auctions',
  AUCTION_DETAILS: (auctionId: string) => `/auctions/${auctionId}`,
  CREATE_AUCTION: (cardId: string) => `/auctions/create/${cardId}`,
  EDIT_AUCTION: (auctionId: string) => `/auctions/edit/${auctionId}`,
  CHATS: '/chats',
  CARDS: '/cards',
  CREATE_CARD: '/create-card',
  SETS: '/sets',
  CREATE_SET: '/set-create',
  STATISTICS: '/statistics',
  USERS: '/users',
  TRANSACTIONS: '/transactions',
  LOCATIONS: '/locations',
  CREATE_LOCATION: '/locations/create',
  EPISODES: '/episodes',
  CREATE_EPISODE: '/episodes/create',
};
