export const ROUTES = {
  SIGN_UP: '/signup',
  SIGN_IN: '/signin',
  USER_CARDS: '/',
  USER_CARDS_DETAILS: '/:cardId',
  PROFILE: '/profile',
  AUCTIONS: '/auctions',
  CHATS: '/chats',
  CARDS: '/cards',
  CREATE_CARD: '/create-card',
  SETS: '/sets',
  STATISTICS: '/statistics',
  USERS: '/users',
  TRANSACTIONS: '/transactions',
};
